Minor improvements to error reporting

diff --git a/shmig b/shmig
--- a/shmig
+++ b/shmig
@@ -446,7 +446,7 @@ create(){
   [[ $# -eq 1 ]] || die "${LRED}create takes exactly one argument${CLEAR}: $ME create <name>"
   local name="$1"
 
-  echo "$name" | grep -E -qi '^[a-z0-9_. -]+$' || die "${LRED}invalid migration name:${CLEAR} $name"
+  echo "$name" | grep -E -qi '^[a-z0-9_. -]+$' || die "${LRED}invalid migration name:${CLEAR} $name. Name must match ^[a-z0-9_. -]+$."
 
   # As of 4/28/2014, seconds since epoch has ten digits.
   find_migrations -name "*[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-$name.sql" \
